### ISSUE TITLE
Update README.md API description

### ISSUE THREAD

**Issue by suraneti** [kulapio/libra-service#9]
I guess we should provide API information (endpoint name, method, parameter, an example) for users.

**Comment by totiz** [comment]
Good, could you do a PR for this, we have public postman that you can refer to https://documenter.getpostman.com/view/1671913/S1a32SZ5?version=latest#fb989ae4-f905-4a0d-869e-540f3e13c18a

**Comment by suraneti** [comment]
@totiz yes, I will do it.

**Comment by suraneti** [comment]
@totiz I've created PR #12.

**Comment by totiz** [comment]
Done merged ^^.
